{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "ks-core.fullname" . }}
  namespace: {{ .Release.Namespace }}
{{- if eq .Values.tls "external" }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false" # turn off ssl redirect for external.
{{- end }}
spec:
  rules:
  - host: {{ .Values.hostname }}
    http:
      paths:
      - pathType: ImplementationSpecific
        backend:
          service:
            name: ks-console
            port:
              number: 80
{{- if eq .Values.tls "ingress" }}
  tls:
  - hosts:
    - {{ .Values.hostname }}
    secretName: {{ .Values.ingress.tls.secretName }}
{{- end }}
{{- end }}
