{{- if and .Values.ingress.enabled (eq .Values.ingress.tls.secretName "ks-console-ingress-cert") }}
{{- $cert := genSelfSignedCert .Values.hostname nil nil 3650 -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: ks-console-ingress-cert
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  tls.crt: {{ b64enc $cert.Cert }}
  tls.key: {{ b64enc $cert.Key }}
{{- end }}
