name: BuildContainerImage

on:
  push:
    branches:
      - 'master'
      - 'release-*'
      - 'qkcp'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'qkcp'
      - 'master'
      - 'release-*'

jobs:
  build:
    name: Verify and Test
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Verify
        run: make verify-all

      - name: Unit test
        run: make all

