name: CI

on:
  push:
    branches:
      - 'master'
      - 'release-*'
      - 'kse-3.3'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'kse-3.3'
      - 'master'
      - 'release-*'

jobs:
  build:
    name: Verify and Test
    runs-on: self-hosted
    env:
      GO111MODULE: on
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install goimports
        run: go get -u golang.org/x/tools/cmd/goimports 

      - name: Downloading go dependencies
        run: go mod vendor

      - name: Verify
        run: make verify-all

      - name: Build
        run: make all

      - name: Make OpenAPI Spec
        run: make openapi

